image: rust:1.26-jessie

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - cargo
          - rust-target
        script:
          - echo $CARGO_HOME
          - cargo install rustfmt
          - cargo fmt -- --write-mode=diff
          - cargo build
          - cargo test
    - step:
        name: Build and deploy
        deployment: test
        caches:
          - cargo
          - rust-target
        script:
          - cargo build --release
          - export HOST=iptvdream.zapto.org
          - scp ./target/release/epg-server $USERNAME@$HOST:~/epg-server.tmp
          - ssh $USERNAME@$HOST mv epg-server.tmp epg-server
          - ssh $USERNAME@$HOST sudo /bin/systemctl restart epg-server

definitions:
  caches:
    cargo: /usr/local/cargo # CARGO_HOME
    rust-target: $BITBUCKET_CLONE_DIR/target
