image: rust:1.32-stretch

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - cargo
          - rust-target
        script:
          - apt-get update && apt-get install -y mongodb-clients
          - mongo epg ./setup/create-user.js
          - echo $CARGO_HOME
          - rustup component add rustfmt-preview
          - cargo fmt -- --check
          - cargo build
          - cargo test
        services:
          - mongo
    - step:
        name: Build and deploy
        deployment: test
        caches:
          - cargo
          - rust-target
        script:
          - OPENSSL_STATIC=1 OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu OPENSSL_INCLUDE_DIR=/usr/include/openssl
            cargo build --release
          - export HOST=iptvdream.zapto.org
          - scp ./target/release/epg-server $USERNAME@$HOST:~/epg-server.tmp
          - ssh $USERNAME@$HOST mv epg-server.tmp epg-server
          - ssh $USERNAME@$HOST sudo /bin/systemctl restart epg-server epg-server-soveni

definitions:
  caches:
    cargo: /usr/local/cargo # CARGO_HOME
    rust-target: $BITBUCKET_CLONE_DIR/target

  services:
    mongo:
      image: mongo:4-xenial
