image: rust:1.26-jessie

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - cargo
        script:
          - echo $CARGO_HOME
          - cargo build
          - cargo test
    - step:
        name: Build and deploy
        deployment: test
        caches:
          - cargo
        script:
          - cargo build --release
          - export HOST=iptvdream.zapto.org
          - scp ./target/release/epg-server $USERNAME@$HOST:~/epg-server
          - ssh $USERNAME@$HOST sudo /bin/systemctl restart epg-server

definitions:
  caches:
    cargo: /usr/local/cargo # CARGO_HOME
