[package]
name = "epg-server"
version = "0.1.0"
authors = ["Alex Maystrenko <alexeytech@gmail.com>"]

[dependencies]
iron = "*"
router = "*"
persistent = "*"
urlencoded = "*"
reqwest = "0.8"
hyper = "*"
flate2 = "1.0"
xml-rs = "0.7.0"
chrono = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
timer = "0.2"
clap = "2"
bson = "0.13"
mongodb = "0.3"

[profile.dev]
opt-level = 1
