[package]
name = "epg-server"
version = "0.1.0"
authors = ["Alex Maystrenko <alexeytech@gmail.com>"]

[dependencies]
iron = "*"
router = "*"
persistent = "*"
urlencoded = "*"
reqwest = "0.9"
hyper = "*"
hyperx = "0.14"
flate2 = "1.0"
quick-xml = "0.12"
chrono = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
timer = "0.2"
clap = "2"
bson = "0.13"
mongodb = "0.3"
rusqlite = "*"

[profile.dev]
opt-level = 1
