version: 2
jobs:
  build:
    docker:
      - image: rust:1.32-stretch
      - image: circleci/mongo:4-xenial
    steps:
      - checkout
      - restore_cache:
          key: rust-cache
      - run:
          name: Build and test
          command: |
            apt-get update && apt-get install -y mongodb-clients
            mongo epg ./setup/create-user.js
            echo $CARGO_HOME
            rustup component add rustfmt-preview
            cargo fmt -- --check
            cargo build
            cargo test
      - add_ssh_keys:
          fingerprints:
            - "45:16:fd:9e:94:b8:84:59:ae:5b:50:6e:e7:e2:e5:09"
      - run:
          name: Add fingerprint
          command: echo $UPDATE_FINGERPRINT >> ~/.ssh/known_hosts
      - run:
          name: Release build
          command: >
            OPENSSL_STATIC=1 OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu OPENSSL_INCLUDE_DIR=/usr/include/openssl
            cargo build --release
      - save_cache:
          key: rust-cache
          paths:
            - "/usr/local/cargo"
            - "./target"
      - run:
          name: Deploy
          command: |
            scp ./target/release/epg-server $USERNAME@$HOST:~/epg-server.tmp
            ssh $USERNAME@$HOST mv epg-server.tmp epg-server
            ssh $USERNAME@$HOST sudo /bin/systemctl restart epg-server epg-server-soveni
