version: 2
jobs:
  build:
    docker:
      - image: rust:1.32-stretch
      - image: circleci/mongo:3-stretch
    steps:
      - checkout
      - run:
          name: Build and test
          command: |
            echo $CARGO_HOME
            rustup component add rustfmt-preview
            cargo fmt -- --check
            cargo build
            ./setup.sh
            cargo test
