version: 2
jobs:
  build:
    docker:
      - image: rust:1.30-stretch
    steps:
      - checkout
      - run:
          name: Build and test
          command: |
            echo $CARGO_HOME
            rustup component add rustfmt-preview
            cargo fmt -- --check
            cargo build
            cargo test
