version: 2
jobs:
  build:
    docker:
      - image: rust:1.26-jessie
    steps:
      - checkout
      - run:
          name: Build and test
          command: |
            echo $CARGO_HOME
            rustup component add rustfmt-preview
            cargo fmt -- --write-mode=diff
            cargo build
            cargo test
